title: Georgia Harbor-Collins

author:
  name: Georgia Harbor-Collins
  email: georgia.harbor-collins@uconn.edu

description: >
  Math Dept. UConn, 341 Mansfield Road Unit 1009, Storrs, CT 06269-1009.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations:
    - import

minima:
  skin: classic
  nav_pages:
    - index.md
    - papers.md

show_excerpts: false